### ISSUE TITLE
thread safety of Kafka.Client.Consumers.ZookeeperConnector.CommitOffsets()

### ISSUE THREAD

**Issue by ewhauser** [ExactTargetDev/kafka#1]
We are getting the following error when testing the client:

```
Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Kafka.Client.Consumers.ZookeeperConsumerConnector.CommitOffsets() in D:\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Consumers\ZookeeperConsumerConnector.cs:line 110
   at Kafka.Client.Consumers.ZookeeperConsumerConnector.AutoCommit() in D:\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Consumers\ZookeeperConsumerConnector.cs:line 135
```

**Comment by bosman** [comment]
Fixed. Please rerun tests on your side to confirm and close the ticket.
