### ISSUE TITLE
ObjectDisposedException of ZookeepConsumerConnector

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#12]
Nearly all of my testing gets a lot of these exceptions once I started testing in an environment that is using a cluster of more than one zookeeper instance for Kafka.

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ZookeeperConsumerConnector'.
   at Kafka.Client.Consumers.ZookeeperConsumerConnector.EnsuresNotDisposed()
   at Kafka.Client.Consumers.ZookeeperConsumerConnector.AutoCommit()
   at Kafka.Client.Utils.KafkaScheduler.HandleCallback(Object o)
   at System.Threading._TimerCallback.TimerCallback_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading._TimerCallback.PerformTimerCallback(Object state)

Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ZookeeperConsumerConnector'.
   at Kafka.Client.Consumers.ZookeeperConsumerConnector.EnsuresNotDisposed()
   at Kafka.Client.Consumers.ZookeeperConsumerConnector.AutoCommit()
   at Kafka.Client.Utils.KafkaScheduler.HandleCallback(Object o)
   at System.Threading._TimerCallback.TimerCallback_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading._TimerCallback.PerformTimerCallback(Object state)

**Comment by bosman** [comment]
We got quite a bit of these as well. We have made some changes and based on our tests this is fixed. I'm not getting it any more. Please retest. If you still get the issue please provide the test case code or description for us to reproduce.

**Comment by tteats** [comment]
I haven't seen this in awhile. Closing.
