### ISSUE TITLE
Losing a connection the the kafka server needs better exception handling

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#13]
Scenario:

Start 2 or more nodes and start producing messages on several threads (I used 20 threads with 20 different Producer instances). While producing, stop one of the kafka nodes.  Wait a minute, then turn the server back on.

When doing this, I get mainly 2 exceptions that both can mean about anything. It would be nice if we either restarted the connection or through a KafkaConnectionException with the actual exception as the inner exception. That way I can easily catch this exception and know that I need to re-instantiate a new Producer.

``` csharp
using (var producer = new Producer(config))
            {
                while (true)
                {
                    try
                    {
                        if (cancellationToken.IsCancellationRequested)
                            break;

                        Guid id = Guid.NewGuid();
                        Stats.Incr(Topic + ".producer");

                        var message = id + Pad();
                        var originalMessage = new Message(Encoding.UTF8.GetBytes(message));

                        var producerData = new ProducerData<string, Message>(
                            Topic, originalMessage);
                        producer.Send(producerData);
                        output.WriteLine("{0},{1}", id, DateTime.Now.ToIso8601(DateTimePrecision.Milliseconds));
                        if (sleepMs > 0)
                            Thread.Sleep(sleepMs);
                    }
                    catch (Exception e)
                    {
                        Log.Error(e);
                    }
                }
            }
```

I would like to catch KafkaConnectionException and reconnect.

Here are the exceptions that get thrown on .Send(..)

System.InvalidOperationException: The operation is not allowed on non-connected sockets.
     at System.Net.Sockets.TcpClient.GetStream()
     at Kafka.Client.KafkaConnection.Write(Byte[] data) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\KafkaConnection.cs:line 149
     at Kafka.Client.KafkaConnection.Write(ProducerRequest request) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\KafkaConnection.cs:line 126
     at Kafka.Client.Producers.Sync.SyncProducer.Send(ProducerRequest request) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Sync\SyncProducer.cs:line 92
     at Kafka.Client.Producers.Sync.SyncProducerPool`1.Send(IEnumerable`1 poolData) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Sync\SyncProducerPool.cs:line 182
     at Kafka.Client.Producers.Producer`2.Send(IEnumerable`1 data) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 199
     at Kafka.Client.Producers.Producer`2.Send(ProducerData`2 data) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 215
     at KafkaTest.Producers.GenericGuidProducer.Start(CancellationToken cancellationToken, TextWriter output, Int32 sleepMs) in D:\ExactTargetTools\KafkaTest\Producers\GenericGuidProducer.cs:line 52
# 

System.IO.IOException: Unable to write data to the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
     at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
     --- End of inner exception stack trace ---
     at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
     at Kafka.Client.KafkaConnection.Write(Byte[] data) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\KafkaConnection.cs:line 151
     at Kafka.Client.KafkaConnection.Write(ProducerRequest request) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\KafkaConnection.cs:line 126
     at Kafka.Client.Producers.Sync.SyncProducer.Send(ProducerRequest request) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Sync\SyncProducer.cs:line 92
     at Kafka.Client.Producers.Sync.SyncProducerPool`1.Send(IEnumerable`1 poolData) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Sync\SyncProducerPool.cs:line 182     at Kafka.Client.Producers.Producer`2.Send(IEnumerable`1 data) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 199
     at Kafka.Client.Producers.Producer`2.Send(ProducerData`2 data) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 215
     at KafkaTest.Producers.GenericGuidProducer.Start(CancellationToken cancellationToken, TextWriter output, Int32 sleepMs) in D:\ExactTargetTools\KafkaTest\Producers\GenericGuidProducer.cs:line 55

**Comment by ppekrol** [comment]
I've applied your request (7a569688bbd3580f5729a4bfa9b0e6d9a6192a66)
