### ISSUE TITLE
KeyNotFoundException when a broker goes offline during producer

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#15]
When a broker goes offline, I get tons of the exceptions below:

Repro by using the test tool, then taking a broker offline. This should get plenty of these results if you have several threads producing.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at Kafka.Client.Producers.Sync.SyncProducerPool`1.Send(IEnumerable`1 poolData) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Sync\SyncProducerPool.cs:line 170
at Kafka.Client.Producers.Producer`2.Send(IEnumerable`1 data) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 199
at Kafka.Client.Producers.Producer`2.Send(ProducerData`2 data) in z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 215
at KafkaTest.Producers.GenericGuidProducer.Start(CancellationToken cancellationToken, TextWriter output, Int32 sleepMs) in D:\ExactTargetTools\KafkaTest\Producers\GenericGuidProducer.cs:line 60

**Comment by ppekrol** [comment]
I successfully reproduced this exception several times today, but from other reasons I had to remove zookeeper snapshot, logs, KafkaTest bin/Debug and restart the machine where the zookeeper is and then from unknown reasons the problems does not occur anymore (tried like dozen times).

Can you do similar thing? I also found other bug in the code, so please update your KafkaTest ZooKeeper and Client dlls to the latest version.
