### ISSUE TITLE
Does this project in fact work with .8?  If not, which one does?  Need it somewhat urgently

### ISSUE THREAD

**Issue by winbatch** [ExactTargetDev/kafka#27]
I've tried this library as well as this branch:
https://github.com/tnachen/kafka/tree/feature/et-develop-0.8

And I'm trying to do a simple producer.   It fails and the broker log says this:
[2014-01-09 11:31:20,525] ERROR Closing socket for /<maskedip> because of error (kafka.network.Processor)
java.nio.BufferUnderflowException
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:145)
        at java.nio.ByteBuffer.get(ByteBuffer.java:694)
        at kafka.api.ApiUtils$.readShortString(ApiUtils.scala:38)
        at kafka.api.ProducerRequest$.readFrom(ProducerRequest.scala:33)
        at kafka.api.RequestKeys$$anonfun$1.apply(RequestKeys.scala:34)
        at kafka.api.RequestKeys$$anonfun$1.apply(RequestKeys.scala:34)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:49)
        at kafka.network.Processor.read(SocketServer.scala:345)
        at kafka.network.Processor.run(SocketServer.scala:245)
        at java.lang.Thread.run(Thread.java:722)

Is there a viable C# .8 compatible library out there?

**Comment by ewhauser** [comment]
There is a not a version of this library that currently works with 0.8.  There have been a couple of folks who have had interest in getting the work necessary completed, but no pull requests have been submitted.  I am not aware of any alternative C# implementations (nor should there be any reason to create one - it's a large undertaking to write a compatible client).
