### ISSUE TITLE
ZookeeperClient cannot access disposed object.

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#7]
This happens from time to time when starting back up a consumer. Haven't seen an automatic repro of this yet, however.  This is getting called from a polling thread which is probably why it's hard to figure out exactly why this is happening.

System.ObjectDisposedException: Cannot access a disposed object.  Object name: 'ZooKeeperClient'.
at Kafka.Client.ZooKeeperIntegration.ZooKeeperClient.EnsuresNotDisposed() in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\ZooKeeperIntegration\ZooKeeperClient.cs:line 891
at Kafka.Client.ZooKeeperIntegration.ZooKeeperClient.Process(WatchedEvent e) in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\ZooKeeperIntegration\ZooKeeperClient.Watcher.cs:line 129
at ZooKeeperNet.ClientConnectionEventConsumer.PollEvents() in Z:\tteats\github\zookeeper\src\dotnet\ZooKeeperNet\ClientConnectionEventConsumer.cs:line 87

**Comment by bosman** [comment]
I introduced some locks and this problem stopped to occur in my tests. Please, retest.
