### ISSUE TITLE
NullReferenceException in ZkBrokerPartitionInfo.GetBrokerPartitionInfo

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#8]
I'm getting an exception during publish from time to time.  It looks to be connected to getting disconnected from ZK.  Looking at the stack trace, the null member variable can be null if Reset() gets called internally. Possibly this should be protected.  I think you can figure things out from the stack trace. If you need more info, let me know.  Line numbers should match up.

System.NullReferenceException: Object reference not set to an instance of an object.
     at Kafka.Client.Producers.Partitioning.ZKBrokerPartitionInfo.GetBrokerPartitionInfo(String topic) in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Partitioning\ZKBrokerPartitionInfo.cs:line 101
     at Kafka.Client.Producers.Producer`2.GetPartition(ProducerData`2 dataItem) in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 305
     at Kafka.Client.Producers.Producer`2.Send(IEnumerable`1 data) in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 194
     at ExactTarget.PubSub.Kafka.AsyncKafkaTransport.Publish[T](String topic, T message) in D:\Inetpub\Core\ExactTarget.PubSub\ExactTarget.PubSub\Kafka\AsyncKafkaTransport.cs:line 48

**Comment by bosman** [comment]
I did manage to get this error only few times. I introduced a lock that I think solves the problem. I did not see the error after that, but I may just have been unlucky. Please, see if this commit fixes the issue in your tests. If it does not, please see if you can provide any code sample that is likely to produce the error to help me in further investigation. Thanks.

**Comment by tteats** [comment]
The fix gives me an error when trying to publish anything (error below). I will revert to the older dll and see if I can get a good repro and translate it to a unit test.

System.Threading.LockRecursionException: Recursive read lock acquisitions not allowed in this mode.
     at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(Int32 millisecondsTimeout)
     at System.Threading.ReaderWriterLockSlim.TryEnterReadLock(Int32 millisecondsTimeout)     at Kafka.Client.Producers.Partitioning.ZKBrokerPartitionInfo.BootstrapWithExistingBrokers(String topic) in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Partitioning\ZKBrokerPartitionInfo.cs:line 267
     at Kafka.Client.Producers.Partitioning.ZKBrokerPartitionInfo.GetBrokerPartitionInfo(String topic) in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Partitioning\ZKBrokerPartitionInfo.cs:line 126
     at Kafka.Client.Producers.Producer`2.GetPartition(ProducerData`2 dataItem) in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 305
     at Kafka.Client.Producers.Producer`2.Send(IEnumerable`1 data) in Z:\tteats\github\kafka\clients\csharp\src\Kafka\Kafka.Client\Producers\Producer.cs:line 194
     at ExactTarget.PubSub.Kafka.AsyncKafkaTransport.Publish[T](String topic, T message) in d:\Inetpub\Core\ExactTarget.PubSub\ExactTarget.PubSub\Kafka\AsyncKafkaTransport.cs:line 48

**Comment by bosman** [comment]
Sorry for the new error I introduced - didn't get it in my tests. A unit test reproducing the original bug would be very appreciated. So far I did not manage to create a test case that would produce the bug on every run. In fact I only got it few times when I manipulated the debuger but never on a run without debug code breaks.

**Comment by bosman** [comment]
Ok, we have managed to create a test case to produce the original bug. We also managed to get the second bug. They are both corrected now. Please, check the latest commit.

**Comment by tteats** [comment]
Thanks @bonman,
I will check this out this morning.

On 5/15/12 2:16 AM, "bosman"
<reply+i-4463398-341749b9780bb1eea0593da0ae753c75fc4d195c-338974@reply.gith
ub.com> wrote:
